name: f_lib
description: Functional library for Flutter Global Summit 21 Vol 2
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
